# Generated by Django 5.1.5 on 2025-01-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_sudokusers_sudokupuzzle_users_userspuzzle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersPuzzle',
        ),
    ]
