# Generated by Django 5.1.5 on 2025-01-24 20:32

import sudoku.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_delete_userspuzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudokupuzzle',
            name='temp_puzzle',
            field=models.JSONField(blank=True, null=True, validators=[sudoku.validators.check9x9]),
        ),
    ]
