# Generated by Django 5.1.5 on 2025-01-31 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_sudokupuzzle_temp_puzzle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='puzzles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SudokUsers',
        ),
    ]
